{"uid":"7c3169e3cf3ec80b","name":"test_xfail","fullName":"test.allure_status_test#test_xfail","historyId":"f37ad0a404a467cce5f63f51cfe5219f","time":{"start":1673971175741,"stop":1673971175741,"duration":0},"status":"skipped","statusMessage":"XFAIL Some xfail reason\n\nAssertionError: Assertion failed\nassert False","statusTrace":"@pytest.mark.xfail(reason=\"Some xfail reason\")\n    def test_xfail():\n>       assert False, \"Assertion failed\"\nE       AssertionError: Assertion failed\nE       assert False\n\ntest/allure_status_test.py:24: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"tag","value":"@pytest.mark.xfail(reason='Some xfail reason')"},{"name":"parentSuite","value":"test"},{"name":"suite","value":"allure_status_test"},{"name":"host","value":"fv-az733-964"},{"name":"thread","value":"2308-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test.allure_status_test"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":0,"broken":0,"skipped":4,"passed":0,"unknown":0,"total":4},"items":[{"uid":"79568cb763cdc806","reportUrl":"https://sreesar.github.io/project/27//#testresult/79568cb763cdc806","status":"skipped","statusDetails":"XFAIL Some xfail reason\n\nAssertionError: Assertion failed\nassert False","time":{"start":1673971116035,"stop":1673971116035,"duration":0}},{"uid":"425a4e7fdfca27cd","reportUrl":"https://sreesar.github.io/project/26//#testresult/425a4e7fdfca27cd","status":"skipped","statusDetails":"XFAIL Some xfail reason\n\nAssertionError: Assertion failed\nassert False","time":{"start":1673971052179,"stop":1673971052179,"duration":0}},{"uid":"649d0b97b455f842","reportUrl":"https://sreesar.github.io/project/25//#testresult/649d0b97b455f842","status":"skipped","statusDetails":"XFAIL Some xfail reason\n\nAssertionError: Assertion failed\nassert False","time":{"start":1673971001999,"stop":1673971001999,"duration":0}}]},"tags":["@pytest.mark.xfail(reason='Some xfail reason')"]},"source":"7c3169e3cf3ec80b.json","parameterValues":[]}